from __future__ import annotations

from core.tools.common_helpers import (
    Any,
    ArtifactInfo,
    CRS,
    _build_mask_from_query,
    _align_crs,
    _estimate_projected_gdf,
    _prepare_join_frame,
    _tool_error_from_validation,
    _tool_internal_error,
    gpd,
    pd,
    rasterio,
    tool,
    tool_result_error,
    tool_result_ok,
    uuid4,
    validate_crs,
    validate_dataset_exists,
    validate_geometry_type,
    validate_numeric_fields,
    validate_output_path,
    validate_raster_readable,
    validate_required_fields,
    validate_vector_readable,
)
