import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const renderer = readFileSync(resolve(root, 'src/components/ChatMessageRenderer.tsx'), 'utf8');
const taskStatusCard = readFileSync(resolve(root, 'src/components/chat/task-card/TaskStatusCard.tsx'), 'utf8');
const taskThinkingSummary = readFileSync(resolve(root, 'src/components/chat/task-card/TaskThinkingSummary.tsx'), 'utf8');
const taskProcessTimeline = readFileSync(resolve(root, 'src/components/chat/task-card/TaskProcessTimeline.tsx'), 'utf8');
const taskActionBar = readFileSync(resolve(root, 'src/components/chat/task-card/TaskActionBar.tsx'), 'utf8');
const taskResultGroups = readFileSync(resolve(root, 'src/components/chat/task-card/TaskResultGroups.tsx'), 'utf8');
const taskDiagnosticsDetails = readFileSync(resolve(root, 'src/components/chat/task-card/TaskDiagnosticsDetails.tsx'), 'utf8');
const panel = readFileSync(resolve(root, 'src/components/ChatPanel.tsx'), 'utf8');
const conversationHeader = readFileSync(resolve(root, 'src/components/chat/ChatConversationHeader.tsx'), 'utf8');
const messageList = readFileSync(resolve(root, 'src/components/chat/ChatMessageList.tsx'), 'utf8');
const composerFooter = readFileSync(resolve(root, 'src/components/chat/ChatComposerFooter.tsx'), 'utf8');
const realtimeHook = readFileSync(resolve(root, 'src/components/chat/useChatRealtimeEvents.ts'), 'utf8');
const downloadsHook = readFileSync(resolve(root, 'src/components/chat/useChatDownloads.ts'), 'utf8');
const promptStreamActionHook = readFileSync(resolve(root, 'src/components/chat/useChatPromptStreamAction.ts'), 'utf8');
const api = readFileSync(resolve(root, 'src/lib/api.ts'), 'utf8');
const css = readFileSync(resolve(root, 'src/index.css'), 'utf8');

assert.match(renderer, /import \{ TaskStatusCard \} from '\.\/chat\/task-card\/TaskStatusCard'/, 'ChatMessageRenderer must delegate unified task card rendering to a focused component');
assert.doesNotMatch(renderer, /function TaskStatusCard/, 'ChatMessageRenderer should not own the task card body after phase 2 extraction');
assert.match(taskStatusCard, /export function TaskStatusCard/, 'TaskStatusCard component should live in its own file');
assert.match(taskProcessTimeline, /export function TaskProcessTimeline/, 'TaskProcessTimeline boundary should own the visible process timeline');
assert.match(taskStatusCard, /function buildAgentProcessSteps/, 'Task card must derive detailed process steps from task metadata');
assert.match(taskStatusCard, /data-testid="task-card-a3-header"/, 'Task card should expose a stable A3 header for screenshot checks');
assert.match(taskStatusCard, /task-card-a3-identity/, 'Task card should expose a responsive identity group');
assert.match(taskThinkingSummary, /export function TaskThinkingSummary/, 'TaskThinkingSummary boundary should own public process thinking');
assert.match(taskActionBar, /export function TaskActionBar/, 'TaskActionBar boundary should own task actions');
assert.match(taskResultGroups, /export function TaskResultGroups/, 'TaskResultGroups boundary should own task result grouping');
assert.match(taskDiagnosticsDetails, /export function TaskDiagnosticsDetails/, 'TaskDiagnosticsDetails boundary should own diagnostics details');
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.task-card-a3-identity\s*\{[\s\S]*flex-basis:\s*100%/, 'Narrow task cards should give the title and summary a full row');
assert.match(taskThinkingSummary, /data-testid="task-card-public-process"/, 'TaskThinkingSummary should render a public process section');
assert.match(taskStatusCard, /data-testid="task-card-result-dock"/, 'Task card should render a result dock aligned with the right rail');
assert.match(taskStatusCard, /task-card-status-spine/, 'Task card should share the status-spine visual language with the A3 rail');
assert.match(taskThinkingSummary, /\u516c\u5f00\u8fc7\u7a0b/, 'TaskThinkingSummary should label public thinking as a public process, not hidden reasoning');
assert.match(taskProcessTimeline, /\u5904\u7406\u8fc7\u7a0b/, 'TaskProcessTimeline must label the visible agent process section in Chinese');
assert.match(taskStatusCard, /正在检查输入数据/, 'Task card must explain input/data validation as a visible step');
assert.match(taskStatusCard, /注册成果与地图图层/, 'Task card must explain artifact and map layer registration');
assert.match(taskStatusCard, /GIS 任务/, 'TaskStatusCard must present a user-readable GIS task header');
assert.match(taskResultGroups, /\u4efb\u52a1\u7ed3\u679c/, 'ResultGroups must present a user-readable result section');
assert.match(taskResultGroups, /\u4e0b\u4e00\u6b65\u5efa\u8bae/, 'ResultGroups must render canonical next_action_suggestions');
assert.match(renderer, /interaction_type/, 'ChatMessageRenderer must consume explicit backend interaction_type metadata');
assert.match(taskResultGroups, /function TaskResultGroups/, 'Task result grouping should live in TaskResultGroups');
assert.match(taskResultGroups, /\u63a8\u8350\u67e5\u770b/, 'ResultGroups must include the recommended group');
assert.match(taskResultGroups, /\u6570\u636e\u7ed3\u679c/, 'ResultGroups must include the data group');
assert.match(taskResultGroups, /\u56fe\u50cf\u9884\u89c8/, 'ResultGroups must include the image preview group');
assert.match(taskResultGroups, /\u6a21\u578b\u4e0e\u62a5\u544a/, 'ResultGroups must include the model/report group');
assert.match(taskResultGroups, /\u4e0b\u8f7d\u63a8\u8350\u7ed3\u679c/, 'ResultGroups must expose a recommended download action');
assert.match(taskResultGroups, /\u4e0b\u8f7d\u5168\u90e8\u7ed3\u679c/, 'ResultGroups must expose an all-results download action');
assert.match(renderer, /presentationResult \|\| userResult/, 'PresentationResult must remain preferred over user_facing_result');
assert.doesNotMatch(renderer, /JSON\.stringify\([^)]*normalized_results/i, 'Chat UI must not render raw normalized_results');
assert.match(taskStatusCard, /confirmedActionId/, 'Confirmation actions must use structured confirmed action IDs');
assert.match(taskActionBar, /onConfirmAction\?\.\(confirmationPrompt, confirmedActionId\)/, 'Confirmation button must use the structured confirmed action ID');
assert.match(taskActionBar, /onRetry\?\.\(jobId\)/, 'Task retry button must call the structured retry handler with job_id');
assert.match(taskActionBar, /canCancelTask/, 'Task card must expose cancel action for cancellable running or queued jobs');
assert.doesNotMatch(taskActionBar, /status === 'failed' && <button[^]*onClarification\?\.\('retry'/, 'Failed task retry must not be routed as a clarification free-text action');
assert.doesNotMatch(renderer, /sendPrompt\(['"`]继续/, 'Confirmation button must not submit a free-text continue request');

const chatModeIndex = composerFooter.indexOf('interaction-mode-chat');
const toolModeIndex = composerFooter.indexOf('interaction-mode-tool');
const composerIndex = composerFooter.indexOf('<ChatComposer');
assert.match(panel, /<ChatComposerFooter/, 'ChatPanel should render the composer footer component');
assert.ok(chatModeIndex >= 0 && chatModeIndex < composerIndex, 'Mode segmented control must be rendered before the composer');
assert.ok(toolModeIndex >= 0 && toolModeIndex < composerIndex, 'Tool mode button must be rendered before the composer');
assert.match(messageList, /function ThinkingStatusCard/, 'ChatMessageList must show a real-time status card while the assistant is working');
assert.match(conversationHeader, /RealtimeSyncIndicator/, 'ChatConversationHeader must expose realtime connection state');
assert.match(panel, /applyRealtimeEvent/, 'ChatPanel must merge realtime events into existing messages');
assert.match(panel, /useChatRealtimeEvents/, 'ChatPanel should delegate realtime SSE lifecycle to a focused hook');
assert.doesNotMatch(panel, /realtimeEventSourceRef/, 'ChatPanel should not own the EventSource ref after realtime hook extraction');
assert.match(panel, /phase: event\.phase/, 'Realtime task events must preserve backend phase for the visible process timeline');
assert.match(panel, /current_step: event\.current_step/, 'Realtime task events must preserve backend current_step for the visible process timeline');
assert.match(panel, /progress: event\.progress/, 'Realtime task events must preserve backend progress for the visible process timeline');
assert.match(realtimeHook, /export function useChatRealtimeEvents/, 'Realtime SSE lifecycle should live in useChatRealtimeEvents');
assert.match(realtimeHook, /api\.replayChatEvents/, 'Realtime hook must replay missed events for reconnect recovery');
assert.match(realtimeHook, /api\.openChatEventStream/, 'Realtime hook must subscribe to session task SSE events');
assert.match(realtimeHook, /eventIdsRef/, 'Realtime hook must own event de-duplication state');
assert.match(realtimeHook, /taskVersionRef/, 'Realtime hook must own stale-version gating');
assert.match(api, /phase\?: string/, 'RealtimeChatEvent must type backend phase updates');
assert.match(api, /heartbeat_at\?: string/, 'RealtimeChatEvent must type backend heartbeat updates');
assert.match(promptStreamActionHook, /api\.streamChat/, 'Prompt stream hook must use the POST SSE chat stream');
assert.match(realtimeHook, /api\.openChatEventStream/, 'Realtime hook must subscribe to session task SSE events');
assert.match(panel, /messageMatchesRealtimeEvent/, 'Realtime events must target an existing assistant message');
assert.match(panel, /messageIsToolTask/, 'ChatPanel must identify tool task messages without frontend keyword detection');
assert.match(panel, /mergeTaskCardUpdate/, 'ChatPanel must merge task state changes into the existing task card');
assert.match(panel, /messageMatchesConfirmation/, 'Confirmation responses must target the original awaiting-confirmation card');
assert.match(panel, /messageMatchesJob/, 'Download job updates must target the original running task card');
assert.match(panel, /useChatDownloads/, 'ChatPanel should delegate download job controls to a focused hook');
assert.doesNotMatch(panel, /setGSCloudLoginOpen|setPendingLoginJobId|setResumeReadyJobIds|api\.resumeDownloadJob|api\.cancelDownloadJob|api\.retryDownloadJob/, 'ChatPanel should not own GSCloud login/download control state after hook extraction');
assert.match(downloadsHook, /export function useChatDownloads/, 'Download controls should live in useChatDownloads');
assert.match(downloadsHook, /reason: 'download_success'[\s\S]*mergeTaskCardUpdate/, 'Download completion must update the existing task card');
assert.match(downloadsHook, /api\.resumeDownloadJob\(jobId\)/, 'Download hook must resume jobs through the backend endpoint');
assert.match(downloadsHook, /api\.cancelDownloadJob\(jobId, userId, .*sessionId\)/, 'Download hook cancel must pass session_id');
assert.match(downloadsHook, /api\.retryDownloadJob\(jobId, userId, sessionId\)/, 'Download hook retry must call backend retry endpoint with session_id');
assert.match(downloadsHook, /const retryDownload = async \(jobId: string\)/, 'Download hook must expose a structured retry handler');
assert.match(panel, /retryDownload/, 'ChatPanel must still pass the structured retry handler through to the message list');
assert.match(messageList, /onRetry=\{retryDownload\}/, 'Task card must receive the structured retry handler');
assert.match(messageList, /max-w-\[min\(66%,34rem\)\]/, 'User message bubbles should remain compact instead of occupying the whole row');
assert.doesNotMatch(panel, /Boolean\(meta\.presentation_result\)/, 'Answer-only PresentationResult must not promote a chat message into a tool task card');
assert.doesNotMatch(renderer, /Boolean\(presentationResult\)/, 'Answer-only PresentationResult must render as conversation/result content, not a tool task card');

assert.match(api, /artifactMetadata/, 'Artifact display must resolve metadata by artifact_id');
assert.match(api, /downloadArtifactById/, 'Artifact downloads must go through the backend artifact resolver');
assert.match(api, /streamChat/, 'API client must expose chat SSE streaming');
assert.match(api, /openChatEventStream/, 'API client must expose task SSE subscription');
assert.match(api, /replayChatEvents/, 'API client must expose event replay for reconnect recovery');
assert.match(renderer, /chat-streaming-placeholder/, 'Chat renderer must show a streaming placeholder');
assert.match(renderer, /chat-streaming-cursor/, 'Chat renderer must show an active streaming cursor');

console.log('chatTaskCardAndResults.test.mjs passed');
