import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile('src/components/ChatPanel.tsx', 'utf8');
const sendPromptSource = source.match(/const sendPrompt = async[\s\S]*?\n  const confirmAction =/)?.[0] || '';
const chatSessionsHookSource = await readFile('src/components/chat/useChatSessions.ts', 'utf8');
const workspaceMentionsHookSource = await readFile('src/components/chat/useChatWorkspaceMentions.ts', 'utf8');
const resizeHookSource = await readFile('src/components/chat/useChatPanelResize.ts', 'utf8');
const autoScrollHookSource = await readFile('src/components/chat/useChatAutoScroll.ts', 'utf8');
const externalPromptHookSource = await readFile('src/components/chat/useChatExternalPrompt.ts', 'utf8');
const editingHookSource = await readFile('src/components/chat/useChatEditing.ts', 'utf8');
const thesisWorkflowHookSource = await readFile('src/components/chat/useChatThesisWorkflow.ts', 'utf8');
const interactionModeActionHookSource = await readFile('src/components/chat/useChatInteractionModeAction.ts', 'utf8');
const newSessionActionHookSource = await readFile('src/components/chat/useChatNewSessionAction.ts', 'utf8');
const switchSessionActionHookSource = await readFile('src/components/chat/useChatSwitchSessionAction.ts', 'utf8');
const deleteSessionActionHookSource = await readFile('src/components/chat/useChatDeleteSessionAction.ts', 'utf8');
const mapCommandActionHookSource = await readFile('src/components/chat/useChatMapCommandAction.ts', 'utf8');
const promptPreparationHookSource = await readFile('src/components/chat/useChatPromptPreparation.ts', 'utf8');
const promptStreamActionHookSource = await readFile('src/components/chat/useChatPromptStreamAction.ts', 'utf8');
const confirmationActionHookSource = await readFile('src/components/chat/useChatConfirmationAction.ts', 'utf8');
const conversationHeaderSource = await readFile('src/components/chat/ChatConversationHeader.tsx', 'utf8');
const sessionSidebarSource = await readFile('src/components/chat/ChatSessionSidebar.tsx', 'utf8');
const messageListSource = await readFile('src/components/chat/ChatMessageList.tsx', 'utf8');
const layerPanelSource = await readFile('src/components/LayerPanel.tsx', 'utf8');
const localLibraryPanelSource = await readFile('src/components/LocalLibraryPanel.tsx', 'utf8');
const productConsoleSource = await readFile('src/components/ProductConsole.tsx', 'utf8');
const apiSource = await readFile('src/lib/api.ts', 'utf8');

assert.equal(source.includes('PROMPT_GROUPS'), true);
assert.match(source, /useChatWorkspaceMentions/, 'ChatPanel should delegate workspace mentions to a focused hook');
assert.doesNotMatch(source, /api\.workspaceMentions/, 'ChatPanel should not own workspace mention API loading after hook extraction');
assert.match(workspaceMentionsHookSource, /export function useChatWorkspaceMentions/, 'useChatWorkspaceMentions hook should be exported');
assert.match(workspaceMentionsHookSource, /export function normalizeWorkspaceMentions/, 'workspace mention normalization should move with the hook');
assert.match(workspaceMentionsHookSource, /api\.workspaceMentions/, 'workspace mention hook should own API loading');
assert.doesNotMatch(workspaceMentionsHookSource, /raw\.path/, 'workspace mention normalization must not derive public labels from raw paths');
assert.doesNotMatch(apiSource.match(/export type WorkspaceMention[\s\S]*?};/)?.[0] || '', /\n\s*path\?: string;/, 'WorkspaceMention must not expose raw paths to chat context');
assert.match(source, /useChatPanelResize/, 'ChatPanel should delegate floating panel resize behavior to a focused hook');
assert.doesNotMatch(source, /const dragHandle = useMemo/, 'ChatPanel should not own pointer resize handlers inline');
assert.match(resizeHookSource, /export function useChatPanelResize/, 'useChatPanelResize hook should be exported');
assert.match(resizeHookSource, /initialWidth = 430/, 'resize hook should preserve the existing default floating width');
assert.match(resizeHookSource, /minWidth = 360/, 'resize hook should preserve the existing minimum floating width');
assert.match(resizeHookSource, /maxWidth = 680/, 'resize hook should preserve the existing maximum floating width');
assert.match(resizeHookSource, /window\.addEventListener\('pointermove'/, 'resize hook should own pointermove subscription');
assert.match(source, /useChatAutoScroll/, 'ChatPanel should delegate chat list auto-scroll behavior to a focused hook');
assert.doesNotMatch(source, /stickToBottomRef/, 'ChatPanel should not own sticky-bottom scroll state inline');
assert.match(autoScrollHookSource, /export function useChatAutoScroll/, 'useChatAutoScroll hook should be exported');
assert.match(autoScrollHookSource, /scrollHeight - target\.scrollTop - target\.clientHeight < 96/, 'auto-scroll hook should preserve the existing sticky threshold');
assert.match(autoScrollHookSource, /scrollTo\(\{ top: listRef\.current\.scrollHeight, behavior: 'smooth' \}\)/, 'auto-scroll hook should keep smooth scroll-to-bottom behavior');
assert.match(source, /useChatExternalPrompt/, 'ChatPanel should delegate external prompt dispatch to a focused hook');
assert.doesNotMatch(source, /if \(externalPrompt\?\.prompt\) sendPrompt\(externalPrompt\.prompt\)/, 'ChatPanel should not own external prompt effect inline');
assert.match(externalPromptHookSource, /export function useChatExternalPrompt/, 'useChatExternalPrompt hook should be exported');
assert.match(externalPromptHookSource, /externalPrompt\?\.prompt/, 'external prompt hook should preserve prompt presence guard');
assert.match(externalPromptHookSource, /sendPromptRef\.current\(externalPrompt\.prompt\)/, 'external prompt hook should send the provided prompt through the current sender');
assert.match(externalPromptHookSource, /sendPromptRef\.current = sendPrompt/, 'external prompt hook should keep the latest sender without widening dispatch triggers');
assert.match(externalPromptHookSource, /\[externalPrompt\?\.id\]/, 'external prompt hook should retain id-scoped triggering');
assert.match(source, /useChatEditing/, 'ChatPanel should delegate edit-and-regenerate state to a focused hook');
assert.doesNotMatch(source, /const \[editingId, setEditingId\]/, 'ChatPanel should not own editing id state inline');
assert.doesNotMatch(source, /const retryEditedMessage = async/, 'ChatPanel should not own edited-message retry flow inline');
assert.match(editingHookSource, /export function useChatEditing/, 'useChatEditing hook should be exported');
assert.match(editingHookSource, /buildRetryEditedMessageDraft/, 'useChatEditing should preserve retry draft validation');
assert.match(editingHookSource, /api\.retryMessage\(draft\.messageId, draft\.text, userId, currentSessionId\)/, 'useChatEditing should preserve session-scoped retry API call');
assert.match(editingHookSource, /onRetryComplete\(response\)/, 'useChatEditing should hand retry responses back to ChatPanel for existing merge/session reconciliation');
assert.match(source, /mergeServerMessages\(current, normalizeChatMessages\(response\.messages\)\)/, 'ChatPanel should keep stable message merging after edited-message retry');
assert.match(source, /useChatThesisWorkflow/, 'ChatPanel should delegate thesis workflow execution to a focused hook');
assert.doesNotMatch(source, /const runThesisWorkflow = async/, 'ChatPanel should not own thesis workflow execution inline');
assert.match(thesisWorkflowHookSource, /export function useChatThesisWorkflow/, 'useChatThesisWorkflow hook should be exported');
assert.match(thesisWorkflowHookSource, /THESIS_WORKFLOW_PROMPT/, 'thesis workflow hook should preserve the shared workflow prompt');
assert.match(thesisWorkflowHookSource, /api\.runSoilMoistureWorkflow\(userId, currentSessionId\)/, 'thesis workflow hook should preserve the session-scoped workflow API call');
assert.match(thesisWorkflowHookSource, /response\.messages/, 'thesis workflow hook should consume canonical server messages when workflow API returns chat state');
assert.match(thesisWorkflowHookSource, /normalizeChatMessages\(response\.messages\)/, 'thesis workflow hook should normalize workflow chat messages instead of appending a duplicate assistant');
assert.match(thesisWorkflowHookSource, /onWorkflowComplete\(response\)/, 'thesis workflow hook should hand workflow responses back for session and result-panel reconciliation');
assert.match(source, /onWorkflowComplete: handleWorkflowComplete/, 'ChatPanel should reconcile workflow sessions and result panel through a completion callback');
assert.match(thesisWorkflowHookSource, /assistantReplyContent\(response\.reply\)/, 'thesis workflow hook should preserve assistant reply normalization');
assert.match(thesisWorkflowHookSource, /assistantErrorContent\(error\)/, 'thesis workflow hook should preserve assistant error normalization');
assert.match(thesisWorkflowHookSource, /setLastFailedPrompt\(prompt\)/, 'thesis workflow hook should preserve retry prompt on failure');
assert.match(source, /useChatInteractionModeAction/, 'ChatPanel should delegate interaction mode switching to a focused hook');
assert.doesNotMatch(source, /const setInteractionMode = async/, 'ChatPanel should not own interaction mode switch flow inline');
assert.doesNotMatch(source, /await api\.setChatInteractionMode/, 'ChatPanel should not call the interaction mode API directly after hook extraction');
assert.match(interactionModeActionHookSource, /export function useChatInteractionModeAction/, 'useChatInteractionModeAction hook should be exported');
assert.match(interactionModeActionHookSource, /api\.setChatInteractionMode\(currentSessionId, mode, userId\)/, 'interaction mode hook should preserve the session-scoped mode API call');
assert.match(interactionModeActionHookSource, /onModeChanged\(response\)/, 'interaction mode hook should hand responses back to ChatPanel for existing merge/session reconciliation');
assert.match(source, /useChatNewSessionAction/, 'ChatPanel should delegate new session creation to a focused hook');
assert.doesNotMatch(source, /const newSession = async/, 'ChatPanel should not own new-session flow inline');
assert.doesNotMatch(source, /await api\.createChatSession/, 'ChatPanel should not call the new-session API directly after hook extraction');
assert.match(newSessionActionHookSource, /export function useChatNewSessionAction/, 'useChatNewSessionAction hook should be exported');
assert.match(newSessionActionHookSource, /api\.createChatSession\(userId\)/, 'new-session hook should preserve the existing create session API call');
assert.match(newSessionActionHookSource, /onSessionCreated\(response\)/, 'new-session hook should hand responses back to ChatPanel for existing session reconciliation');
assert.match(source, /useChatSwitchSessionAction/, 'ChatPanel should delegate session switching to a focused hook');
assert.doesNotMatch(source, /const switchSession = async/, 'ChatPanel should not own switch-session flow inline');
assert.doesNotMatch(source, /await api\.switchChatSession/, 'ChatPanel should not call the switch-session API directly after hook extraction');
assert.match(switchSessionActionHookSource, /export function useChatSwitchSessionAction/, 'useChatSwitchSessionAction hook should be exported');
assert.match(switchSessionActionHookSource, /api\.switchChatSession\(sessionId, userId\)/, 'switch-session hook should preserve the session-scoped switch API call');
assert.match(switchSessionActionHookSource, /onSessionSwitched\(sessionId, response\)/, 'switch-session hook should hand responses back to ChatPanel for existing session reconciliation');
assert.match(source, /useChatDeleteSessionAction/, 'ChatPanel should delegate session deletion to a focused hook');
assert.doesNotMatch(source, /const deleteSession = async/, 'ChatPanel should not own delete-session flow inline');
assert.doesNotMatch(source, /await api\.deleteChatSession/, 'ChatPanel should not call the delete-session API directly after hook extraction');
assert.doesNotMatch(source, /await api\.clearChatSession/, 'ChatPanel should not call the clear-session API directly after hook extraction');
assert.match(deleteSessionActionHookSource, /export function useChatDeleteSessionAction/, 'useChatDeleteSessionAction hook should be exported');
assert.match(deleteSessionActionHookSource, /api\.deleteChatSession\(currentSessionId, userId\)/, 'delete-session hook should preserve the session-scoped delete API call');
assert.match(deleteSessionActionHookSource, /api\.clearChatSession\(currentSessionId, userId\)/, 'delete-session hook should preserve the single-session clear API call');
assert.match(deleteSessionActionHookSource, /onSessionDeleted\(response\)/, 'delete-session hook should hand responses back to ChatPanel for existing session reconciliation');
assert.match(source, /useChatMapCommandAction/, 'ChatPanel should delegate map text command handling to a focused hook');
assert.doesNotMatch(sendPromptSource, /parseMapTextCommand/, 'sendPrompt should not parse map text commands inline after hook extraction');
assert.match(mapCommandActionHookSource, /export function useChatMapCommandAction/, 'useChatMapCommandAction hook should be exported');
assert.match(mapCommandActionHookSource, /parseMapTextCommand\(text\)/, 'map command hook should preserve map text parsing');
assert.match(mapCommandActionHookSource, /onMapTextCommand\(mapCommand\)/, 'map command hook should preserve the map command callback');
assert.match(source, /useChatPromptPreparation/, 'ChatPanel should delegate prompt preparation to a focused hook');
assert.doesNotMatch(sendPromptSource, /if \(!userId\)/, 'sendPrompt should not own missing-user prompt guard inline after hook extraction');
assert.doesNotMatch(sendPromptSource, /setInput\(''\)/, 'sendPrompt should not clear the input inline after prompt preparation extraction');
assert.match(promptPreparationHookSource, /export function useChatPromptPreparation/, 'useChatPromptPreparation hook should be exported');
assert.match(promptPreparationHookSource, /const text = prompt\.trim\(\)/, 'prompt preparation hook should preserve prompt trimming');
assert.match(promptPreparationHookSource, /if \(!text \|\| thinking\) return null/, 'prompt preparation hook should preserve empty and thinking guards');
assert.match(promptPreparationHookSource, /if \(!userId\)/, 'prompt preparation hook should preserve missing-user guard');
assert.match(promptPreparationHookSource, /setInput\(''\)/, 'prompt preparation hook should preserve input clearing');
assert.match(source, /useChatPromptStreamAction/, 'ChatPanel should delegate prompt streaming to a focused hook');
assert.doesNotMatch(sendPromptSource, /await api\.streamChat/, 'sendPrompt should not call the streaming chat API directly after hook extraction');
assert.match(promptStreamActionHookSource, /export function useChatPromptStreamAction/, 'useChatPromptStreamAction hook should be exported');
assert.match(promptStreamActionHookSource, /buildSendPromptDraft\(\{ text, realtimeSyncState, interactionMode: currentInteractionMode \}\)/, 'prompt stream hook should preserve optimistic draft creation');
assert.match(source, /currentInteractionMode,\s*\n\s*chatContext,/, 'ChatPanel should pass interaction mode into prompt streaming');
assert.match(promptStreamActionHookSource, /await api\.streamChat/, 'prompt stream hook should own the streaming chat API call');
assert.match(promptStreamActionHookSource, /mergeTaskCardUpdate/, 'prompt stream hook should preserve failed task-card updates');
assert.match(promptStreamActionHookSource, /streamLifecycle\.finishTask\(taskId, controller\)/, 'prompt stream hook should finish the stream lifecycle');
assert.match(source, /useChatConfirmationAction/, 'ChatPanel should delegate confirmation execution to a focused hook');
assert.doesNotMatch(source, /const confirmAction = async/, 'ChatPanel should not own confirmation execution inline');
assert.doesNotMatch(source, /await api\.confirmChatAction/, 'ChatPanel should not call the confirmation API directly after hook extraction');
assert.match(confirmationActionHookSource, /export function useChatConfirmationAction/, 'useChatConfirmationAction hook should be exported');
assert.match(confirmationActionHookSource, /await api\.confirmChatAction/, 'confirmation hook should preserve the confirmation API call');
assert.match(confirmationActionHookSource, /onConfirmationComplete\(token, response\)/, 'confirmation hook should hand successful responses back to ChatPanel');
assert.match(confirmationActionHookSource, /streamLifecycle\.finishTask\(taskId, controller\)/, 'confirmation hook should finish the stream lifecycle');
assert.match(source, /<ChatConversationHeader/, 'ChatPanel should render the conversation header through an isolated component');
assert.doesNotMatch(source, /data-testid="floating-chat-toolbar"/, 'ChatPanel should not own the header toolbar JSX inline');
assert.match(conversationHeaderSource, /export function ChatConversationHeader/, 'ChatConversationHeader should be exported');
assert.match(conversationHeaderSource, /data-testid="chat-conversation-header"/, 'ChatConversationHeader should preserve the header test id');
assert.match(conversationHeaderSource, /data-testid="floating-chat-toolbar"/, 'ChatConversationHeader should preserve the floating toolbar test id');
assert.match(conversationHeaderSource, /data-testid="chat-model-selector"/, 'ChatConversationHeader should preserve the model selector');
assert.match(conversationHeaderSource, /data-testid="chat-file-input"/, 'ChatConversationHeader should preserve the hidden file input');
assert.match(conversationHeaderSource, /runThesisWorkflow/, 'ChatConversationHeader should preserve the thesis workflow action');
assert.match(source, /<ChatSessionSidebar/, 'ChatPanel should render the session sidebar through an isolated component');
assert.doesNotMatch(source, /data-testid="chat-session-list"/, 'ChatPanel should not own the page session sidebar JSX inline');
assert.match(sessionSidebarSource, /export function ChatSessionSidebar/, 'ChatSessionSidebar should be exported');
assert.match(sessionSidebarSource, /data-testid="chat-session-list"/, 'ChatSessionSidebar should preserve the session list test id');
assert.match(sessionSidebarSource, /data-testid="chat-new-session"/, 'ChatSessionSidebar should preserve the new session test id');
assert.match(sessionSidebarSource, /sessionDate\(session\)/, 'ChatSessionSidebar should preserve session date labels');
assert.match(source, /<ChatMessageList/, 'ChatPanel should render messages through an isolated message list component');
assert.doesNotMatch(source, /data-testid="chat-empty-state"/, 'ChatPanel should not own the empty-state message list JSX inline');
assert.match(messageListSource, /export function ChatMessageList/, 'ChatMessageList should be exported');
assert.match(messageListSource, /data-testid="chat-empty-state"/, 'ChatMessageList should preserve the empty-state test id');
assert.match(messageListSource, /<ChatMessageRenderer/, 'ChatMessageList should preserve message rendering');
assert.match(messageListSource, /function ThinkingStatusCard/, 'ChatMessageList should preserve the working-status card');
assert.match(messageListSource, /function MessageSourceBadge/, 'ChatMessageList should preserve message source badges');
assert.equal(source.includes('lastFailedPrompt'), true);
assert.equal(messageListSource.includes('重试'), true);
assert.equal(source.includes('检查工作区数据'), true);
assert.equal(source.includes('准备下载数据'), true);
assert.equal(layerPanelSource.includes('if (!user) {'), true);
assert.equal(layerPanelSource.includes('setJobs([]);'), true);

const refreshSessionsSource = chatSessionsHookSource.match(/const refreshSessions = useCallback[\s\S]*?\n  useEffect/)?.[0] || '';
assert.match(refreshSessionsSource, /if \(!requestedUserId\) \{[\s\S]*?setSessions\(\[\]\);[\s\S]*?setCurrentSessionId\(''\);[\s\S]*?onMessagesCleared\(\);[\s\S]*?return;/, 'useChatSessions must not load anonymous chat history before login');
const missingUserBranch = refreshSessionsSource.slice(
  refreshSessionsSource.indexOf('if (!requestedUserId) {'),
  refreshSessionsSource.indexOf('let result = await api.chatSessions')
);
assert.match(missingUserBranch, /setSessions\(\[\]\);[\s\S]*?setCurrentSessionId\(''\);[\s\S]*?onMessagesCleared\(\);[\s\S]*?return;/, 'useChatSessions must return before requesting sessions when userId is initially empty');
assert.match(
  missingUserBranch,
  /if \(!requestedUserId\) \{\s*if \(lastKnownUserIdRef\.current\) \{[\s\S]*?lastSuccessfulSessionUserIdRef\.current = '';[\s\S]*?\}\s*setSessions\(\[\]\);[\s\S]*?return;/,
  'useChatSessions must keep previous-user cleanup separate from the unconditional missing-user return'
);
assert.match(promptPreparationHookSource, /if \(!userId\) \{[\s\S]*?return null;/, 'ChatPanel must not create anonymous chat records before login');
assert.equal(promptStreamActionHookSource.includes('await api.streamChat('), true, 'ChatPanel must send through the streaming chat endpoint');
assert.equal(promptStreamActionHookSource.includes('buildStreamChatContext(chatContext, currentSessionId)'), true, 'Streaming chat must retain session-scoped frontend context');
assert.equal(promptStreamActionHookSource.includes('refreshSessions().catch(() => {})'), true, 'Completed streams must reconcile persisted messages without replacing optimistic history');
assert.equal(source.includes("meta: { reason: 'download_failed' }"), false, 'ChatPanel should not append a duplicate assistant error when a watched download job fails');
assert.equal(layerPanelSource.includes('failure_diagnostic'), false, 'LayerPanel should not render raw failure_diagnostic in the management view path');
assert.equal(layerPanelSource.includes('error_message'), false, 'LayerPanel should not render raw error_message in the management view path');
assert.equal(layerPanelSource.includes('jobView(job)?.user_message'), true, 'LayerPanel should render safe management_view.user_message');
assert.equal(layerPanelSource.includes('job.download_url'), false, 'LayerPanel main download management path must not consume raw job.download_url');
assert.match(layerPanelSource, /api\.artifactMetadata/, 'LayerPanel download actions must resolve artifact_id through the artifact resolver');
assert.match(apiSource, /async importLocalLibrary\(item_ids: string\[\], user_id\?: string, session_id\?: string\)/, 'local library import API helper must accept the current session id');
assert.match(apiSource, /body: JSON\.stringify\(\{ user_id: user_id \|\| '', session_id: session_id \|\| '', item_ids \}\)/, 'local library import API helper must send the current session id');
assert.match(localLibraryPanelSource, /sessionId\?: string/, 'LocalLibraryPanel must accept the current chat session id');
assert.match(localLibraryPanelSource, /api\.importLocalLibrary\(ids, userId \|\| '', sessionId \|\| ''\)/, 'LocalLibraryPanel imports must be scoped to the current session');
assert.doesNotMatch(localLibraryPanelSource, /title=\{item\.path\}|\{item\.path\}/, 'LocalLibraryPanel must not render raw local filesystem paths');
assert.match(layerPanelSource, /<LocalLibraryPanel userId=\{userId\} sessionId=\{sessionId\}/, 'LayerPanel local library imports must stay in the selected session');
assert.match(productConsoleSource, /<LocalLibraryPanel userId=\{userId\} sessionId=\{sessionId \|\| chatContext\?\.session_id\}/, 'ProductConsole local library imports must use the active chat session');

console.log('chat panel experience tests passed');
