import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const composer = await readFile('src/components/ChatComposer.tsx', 'utf8');
const chatPanel = await readFile('src/components/ChatPanel.tsx', 'utf8');
const composerFooter = await readFile('src/components/chat/ChatComposerFooter.tsx', 'utf8');
const voiceHook = await readFile('src/components/chat/useChatVoiceInput.ts', 'utf8');
const css = await readFile('src/index.css', 'utf8');

assert.match(composer, /data-testid="chat-composer"/, 'ChatComposer must keep its root test id');
assert.match(composer, /data-testid="chat-input"/, 'ChatComposer must keep its textarea test id');
assert.match(composer, /data-testid="chat-send"/, 'ChatComposer must keep its send action test id');
assert.match(composer, /data-testid="chat-stop"/, 'ChatComposer must keep its stop action test id');
assert.match(composer, /data-testid="chat-voice"/, 'ChatComposer must keep its voice action test id');
assert.match(chatPanel, /useChatVoiceInput/, 'ChatPanel should delegate browser voice input to a focused hook');
assert.doesNotMatch(chatPanel, /SpeechRecognition|recognitionRef|setVoiceSupported|setVoiceUnavailableReason/, 'ChatPanel should not own browser speech recognition state after hook extraction');
assert.match(voiceHook, /export function useChatVoiceInput/, 'useChatVoiceInput hook should be exported');
assert.match(voiceHook, /SpeechRecognition|webkitSpeechRecognition/, 'Voice hook should own browser speech recognition setup');
assert.match(voiceHook, /isLocalSecureContext/, 'Voice hook should keep secure-context gating for microphone access');
assert.match(composer, /data-testid="chat-mention-trigger"/, 'ChatComposer must keep the workspace mention action test id');
assert.match(composer, /placeholder = '有问题，尽管问'/, 'Composer placeholder should stay Chinese');
assert.match(composer, /aria-label="聊天输入框，按 Enter 发送，按 Shift\+Enter 换行"/, 'Composer textarea aria label should be Chinese');
assert.match(composer, /title=\{uploading \? '正在上传文件' : '上传文件'\}/, 'Upload action title should be Chinese');
assert.match(composer, /title="引用工作区数据"/, 'Mention action title should be Chinese');
assert.match(composer, /title="发送消息，按 Shift\+Enter 换行"/, 'Send action title should be Chinese');
assert.match(composer, /className="chat-composer-input-frame"/, 'Composer controls should be wrapped in a stable command-frame');
assert.match(composer, /className="chat-composer-tool-group"/, 'Secondary tools should be grouped for stable spacing');
assert.match(composer, /className="chat-composer-field"/, 'Textarea should sit in a dedicated flexible field');
assert.match(composer, /className="chat-composer-action-cluster"/, 'Primary send and stop actions should have a stable action cluster');
assert.match(composer, /className="chat-composer-tool-group"[\s\S]*<Plus size=\{20\}[\s\S]*<\/div>\s*<div className="chat-composer-field"/, 'Left side of the unified composer should keep only the upload plus before the text field');
assert.match(composer, /className="chat-composer-action-cluster"[\s\S]*data-testid="chat-mention-trigger"[\s\S]*data-testid="chat-voice"[\s\S]*data-testid="chat-send"/, 'Mention, voice, and send controls should live together on the right side of the input bar');
assert.match(composer, /<Plus size=\{20\}/, 'Upload should use a ChatGPT-like plus affordance inside the unified input bar');
assert.match(composer, /<span className="chat-composer-voice-label">语音<\/span>/, 'Voice control should expose a compact text label inside the input bar');
assert.match(composer, /const minComposerHeight = 44/, 'Unified composer pill should use a compact single-line baseline height');
assert.match(composer, /chat-composer-drag-rail/, 'Drag state should have a dedicated visual rail');
assert.match(composer, /data-dragging=\{dragging \? 'true' : 'false'\}/, 'Root should expose drag state without changing behavior');

assert.match(css, /\.chat-composer-shell\s*\{[\s\S]*border-radius:\s*999px/, 'Composer shell should render as one unified pill surface');
assert.match(css, /\.chat-composer-input-frame\s*\{[\s\S]*grid-template-columns:\s*auto minmax\(0,\s*1fr\) auto[\s\S]*align-items:\s*center/, 'Composer frame must keep tools, flexible input, and action cluster vertically centered');
assert.match(css, /\.chat-composer-tool-group\s*\{[\s\S]*display:\s*inline-flex[\s\S]*border:\s*0/, 'Tool group must blend into the unified input bar without a nested segmented border');
assert.match(css, /\.chat-composer-tool,\s*\n\.chat-composer-submit\s*\{[\s\S]*height:\s*2\.25rem/, 'Tool buttons and submit should share compact centered dimensions');
assert.match(css, /\.chat-composer-tool\.is-voice\s*\{[\s\S]*width:\s*auto[\s\S]*border-radius:\s*999px/, 'Voice control should be a compact pill instead of a square icon only');
assert.match(css, /\.chat-composer-field\s*\{[\s\S]*border:\s*0[\s\S]*background:\s*transparent/, 'Textarea field must merge into the unified composer pill');
assert.match(css, /\.chat-composer-drag-rail\s*\{[\s\S]*position:\s*absolute/, 'Drag rail must be CSS-only and avoid layout shift');
assert.match(css, /\.chat-mention-menu\s*\{[\s\S]*max-width:\s*calc\(100vw - 1rem\)/, 'Mention menu must be viewport constrained');
assert.match(css, /\.chat-mention-list\s*\{[\s\S]*max-height:\s*min\(18rem,\s*42vh\)/, 'Mention list must be height constrained on small screens');
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.chat-composer-input-frame\s*\{[\s\S]*grid-template-columns:\s*auto minmax\(0,\s*1fr\) auto/, 'Mobile composer must retain tools, input, and send columns');
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.chat-composer-action-cluster \.chat-composer-tool\[data-optional="voice"\]/, 'Mobile layout should hide only the optional voice control');
assert.match(chatPanel, /<ChatComposerFooter/, 'ChatPanel should render the bottom composer through a focused footer component');
assert.doesNotMatch(chatPanel, /chat-quick-prompt/, 'ChatPanel should not own quick-prompt footer markup inline');
assert.match(composerFooter, /export function ChatComposerFooter/, 'ChatComposerFooter should be exported');
assert.match(composerFooter, /data-testid="chat-composer-footer"/, 'Composer footer should expose a stable root test id');
assert.match(composerFooter, /isPage \? 'is-page' : 'is-floating'/, 'Composer footer should expose its page or floating layout mode');
assert.doesNotMatch(composerFooter, /chat-quick-prompt/, 'Composer footer should not render quick prompt shortcuts');
assert.doesNotMatch(composerFooter, /quickPrompts|sendPrompt/, 'Composer footer should not keep quick prompt props after removing that UI');
assert.match(composerFooter, /会话模式/, 'Composer footer should label the mode switch in Chinese');
assert.match(composerFooter, /data-testid="interaction-mode-chat"/, 'Composer footer must preserve chat mode test id');
assert.match(composerFooter, /data-testid="interaction-mode-tool"/, 'Composer footer must preserve tool mode test id');
assert.match(css, /\.chat-composer-footer\s*\{[\s\S]*border-top:/, 'Composer footer should have a stable bordered footer surface');
assert.match(css, /\.chat-composer-footer-meta\s*\{[\s\S]*display:\s*flex/, 'Composer footer metadata row should be a flexible row');
assert.match(css, /\.chat-interaction-mode-switch\s*\{[\s\S]*display:\s*inline-flex/, 'Mode switch should have a stable segmented-control style');
assert.match(css, /\.chat-composer-footer\.is-page \.chat-composer-footer-meta\s*\{[\s\S]*flex-direction:\s*column/, 'Page footer should stack metadata instead of squeezing mode copy into a narrow column');
assert.match(css, /\.chat-composer-footer\.is-floating \.chat-composer-footer-meta\s*\{[\s\S]*flex-direction:\s*column/, 'Floating footer should use compact metadata layout even on wide viewports');
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.chat-composer-mode-panel\s*\{[\s\S]*flex-direction:\s*row/, 'Narrow floating footer should keep mode controls and summary on one compact row');

console.log('chatComposerExperience.test.mjs passed');
