import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const renderer = readFileSync(resolve(root, 'src/components/ChatMessageRenderer.tsx'), 'utf8');
const panel = readFileSync(resolve(root, 'src/components/ChatPanel.tsx'), 'utf8');
const conversationHeader = readFileSync(resolve(root, 'src/components/chat/ChatConversationHeader.tsx'), 'utf8');
const messageList = readFileSync(resolve(root, 'src/components/chat/ChatMessageList.tsx'), 'utf8');
const realtimeHook = readFileSync(resolve(root, 'src/components/chat/useChatRealtimeEvents.ts'), 'utf8');
const downloadsHook = readFileSync(resolve(root, 'src/components/chat/useChatDownloads.ts'), 'utf8');
const promptStreamActionHook = readFileSync(resolve(root, 'src/components/chat/useChatPromptStreamAction.ts'), 'utf8');
const api = readFileSync(resolve(root, 'src/lib/api.ts'), 'utf8');

assert.match(renderer, /function TaskStatusCard/, 'ChatMessageRenderer must render tool work through one unified task card');
assert.match(renderer, /function AgentProcessTimeline/, 'Task card must render a detailed user-readable agent process timeline');
assert.match(renderer, /function buildAgentProcessSteps/, 'Task card must derive detailed process steps from task metadata');
assert.match(renderer, /data-testid="task-card-a3-header"/, 'Task card should expose a stable A3 header for screenshot checks');
assert.match(renderer, /data-testid="task-card-public-process"/, 'Task card should render a public process section');
assert.match(renderer, /data-testid="task-card-result-dock"/, 'Task card should render a result dock aligned with the right rail');
assert.match(renderer, /task-card-status-spine/, 'Task card should share the status-spine visual language with the A3 rail');
assert.match(renderer, /公开过程/, 'Task card should label public thinking as a public process, not hidden reasoning');
assert.match(renderer, /处理过程/, 'Task card must label the visible agent process section in Chinese');
assert.match(renderer, /正在检查输入数据/, 'Task card must explain input/data validation as a visible step');
assert.match(renderer, /注册成果与地图图层/, 'Task card must explain artifact and map layer registration');
assert.match(renderer, /GIS 任务/, 'TaskStatusCard must present a user-readable GIS task header');
assert.match(renderer, /任务结果/, 'ResultGroups must present a user-readable result section');
assert.match(renderer, /下一步建议/, 'ResultGroups must render canonical next_action_suggestions');
assert.match(renderer, /interaction_type/, 'ChatMessageRenderer must consume explicit backend interaction_type metadata');
assert.match(renderer, /function ResultGroups/, 'ChatMessageRenderer must group canonical PresentationResult artifacts through ResultGroups');
assert.match(renderer, /推荐查看/, 'ResultGroups must include the recommended group');
assert.match(renderer, /数据结果/, 'ResultGroups must include the data group');
assert.match(renderer, /图像预览/, 'ResultGroups must include the image preview group');
assert.match(renderer, /模型与报告/, 'ResultGroups must include the model/report group');
assert.match(renderer, /下载推荐结果/, 'ResultGroups must expose a recommended download action');
assert.match(renderer, /下载全部结果/, 'ResultGroups must expose an all-results download action');
assert.match(renderer, /presentationResult \|\| userResult/, 'PresentationResult must remain preferred over user_facing_result');
assert.doesNotMatch(renderer, /JSON\.stringify\([^)]*normalized_results/i, 'Chat UI must not render raw normalized_results');
assert.match(renderer, /confirmedActionId/, 'Confirmation actions must use structured confirmed action IDs');
assert.match(renderer, /onConfirmAction\?\.\(confirmationPrompt, confirmedActionId\)/, 'Confirmation button must use the structured confirmed action ID');
assert.match(renderer, /onRetry\?\.\(jobId\)/, 'Task retry button must call the structured retry handler with job_id');
assert.match(renderer, /canCancelTask/, 'Task card must expose cancel action for cancellable running or queued jobs');
assert.doesNotMatch(renderer, /status === 'failed' && <button[^]*onClarification\?\.\('retry'/, 'Failed task retry must not be routed as a clarification free-text action');
assert.doesNotMatch(renderer, /sendPrompt\(['"`]继续/, 'Confirmation button must not submit a free-text continue request');

const chatModeIndex = panel.indexOf('interaction-mode-chat');
const toolModeIndex = panel.indexOf('interaction-mode-tool');
const composerIndex = panel.indexOf('<ChatComposer');
assert.ok(chatModeIndex >= 0 && chatModeIndex < composerIndex, 'Mode segmented control must be rendered before the composer');
assert.ok(toolModeIndex >= 0 && toolModeIndex < composerIndex, 'Tool mode button must be rendered before the composer');
assert.match(messageList, /function ThinkingStatusCard/, 'ChatMessageList must show a real-time status card while the assistant is working');
assert.match(conversationHeader, /RealtimeSyncIndicator/, 'ChatConversationHeader must expose realtime connection state');
assert.match(panel, /applyRealtimeEvent/, 'ChatPanel must merge realtime events into existing messages');
assert.match(panel, /useChatRealtimeEvents/, 'ChatPanel should delegate realtime SSE lifecycle to a focused hook');
assert.doesNotMatch(panel, /realtimeEventSourceRef/, 'ChatPanel should not own the EventSource ref after realtime hook extraction');
assert.match(panel, /phase: event\.phase/, 'Realtime task events must preserve backend phase for the visible process timeline');
assert.match(panel, /current_step: event\.current_step/, 'Realtime task events must preserve backend current_step for the visible process timeline');
assert.match(panel, /progress: event\.progress/, 'Realtime task events must preserve backend progress for the visible process timeline');
assert.match(realtimeHook, /export function useChatRealtimeEvents/, 'Realtime SSE lifecycle should live in useChatRealtimeEvents');
assert.match(realtimeHook, /api\.replayChatEvents/, 'Realtime hook must replay missed events for reconnect recovery');
assert.match(realtimeHook, /api\.openChatEventStream/, 'Realtime hook must subscribe to session task SSE events');
assert.match(realtimeHook, /eventIdsRef/, 'Realtime hook must own event de-duplication state');
assert.match(realtimeHook, /taskVersionRef/, 'Realtime hook must own stale-version gating');
assert.match(api, /phase\?: string/, 'RealtimeChatEvent must type backend phase updates');
assert.match(api, /heartbeat_at\?: string/, 'RealtimeChatEvent must type backend heartbeat updates');
assert.match(promptStreamActionHook, /api\.streamChat/, 'Prompt stream hook must use the POST SSE chat stream');
assert.match(realtimeHook, /api\.openChatEventStream/, 'Realtime hook must subscribe to session task SSE events');
assert.match(panel, /messageMatchesRealtimeEvent/, 'Realtime events must target an existing assistant message');
assert.match(panel, /messageIsToolTask/, 'ChatPanel must identify tool task messages without frontend keyword detection');
assert.match(panel, /mergeTaskCardUpdate/, 'ChatPanel must merge task state changes into the existing task card');
assert.match(panel, /messageMatchesConfirmation/, 'Confirmation responses must target the original awaiting-confirmation card');
assert.match(panel, /messageMatchesJob/, 'Download job updates must target the original running task card');
assert.match(panel, /useChatDownloads/, 'ChatPanel should delegate download job controls to a focused hook');
assert.doesNotMatch(panel, /setGSCloudLoginOpen|setPendingLoginJobId|setResumeReadyJobIds|api\.resumeDownloadJob|api\.cancelDownloadJob|api\.retryDownloadJob/, 'ChatPanel should not own GSCloud login/download control state after hook extraction');
assert.match(downloadsHook, /export function useChatDownloads/, 'Download controls should live in useChatDownloads');
assert.match(downloadsHook, /reason: 'download_success'[\s\S]*mergeTaskCardUpdate/, 'Download completion must update the existing task card');
assert.match(downloadsHook, /api\.resumeDownloadJob\(jobId\)/, 'Download hook must resume jobs through the backend endpoint');
assert.match(downloadsHook, /api\.cancelDownloadJob\(jobId, userId, .*sessionId\)/, 'Download hook cancel must pass session_id');
assert.match(downloadsHook, /api\.retryDownloadJob\(jobId, userId, sessionId\)/, 'Download hook retry must call backend retry endpoint with session_id');
assert.match(downloadsHook, /const retryDownload = async \(jobId: string\)/, 'Download hook must expose a structured retry handler');
assert.match(panel, /retryDownload/, 'ChatPanel must still pass the structured retry handler through to the message list');
assert.match(messageList, /onRetry=\{retryDownload\}/, 'Task card must receive the structured retry handler');
assert.match(messageList, /max-w-\[min\(66%,34rem\)\]/, 'User message bubbles should remain compact instead of occupying the whole row');
assert.doesNotMatch(panel, /Boolean\(meta\.presentation_result\)/, 'Answer-only PresentationResult must not promote a chat message into a tool task card');
assert.doesNotMatch(renderer, /Boolean\(presentationResult\)/, 'Answer-only PresentationResult must render as conversation/result content, not a tool task card');

assert.match(api, /artifactMetadata/, 'Artifact display must resolve metadata by artifact_id');
assert.match(api, /downloadArtifactById/, 'Artifact downloads must go through the backend artifact resolver');
assert.match(api, /streamChat/, 'API client must expose chat SSE streaming');
assert.match(api, /openChatEventStream/, 'API client must expose task SSE subscription');
assert.match(api, /replayChatEvents/, 'API client must expose event replay for reconnect recovery');
assert.match(renderer, /chat-streaming-placeholder/, 'Chat renderer must show a streaming placeholder');
assert.match(renderer, /chat-streaming-cursor/, 'Chat renderer must show an active streaming cursor');

console.log('chatTaskCardAndResults.test.mjs passed');
