import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const composer = await readFile('src/components/ChatComposer.tsx', 'utf8');
const chatPanel = await readFile('src/components/ChatPanel.tsx', 'utf8');
const composerFooter = await readFile('src/components/chat/ChatComposerFooter.tsx', 'utf8');
const conversationHeader = await readFile('src/components/chat/ChatConversationHeader.tsx', 'utf8');
const voiceHook = await readFile('src/components/chat/useChatVoiceInput.ts', 'utf8');
const css = await readFile('src/index.css', 'utf8');

assert.match(composer, /data-testid="chat-composer"/, 'ChatComposer must keep its root test id');
assert.match(composer, /data-testid="chat-input"/, 'ChatComposer must keep its textarea test id');
assert.match(composer, /data-testid="chat-send"/, 'ChatComposer must keep its send action test id');
assert.match(composer, /data-testid="chat-stop"/, 'ChatComposer must keep its stop action test id');
assert.match(composer, /data-testid="chat-voice"/, 'ChatComposer must keep its voice action test id');
assert.match(chatPanel, /useChatVoiceInput/, 'ChatPanel should delegate browser voice input to a focused hook');
assert.doesNotMatch(chatPanel, /SpeechRecognition|recognitionRef|setVoiceSupported|setVoiceUnavailableReason/, 'ChatPanel should not own browser speech recognition state after hook extraction');
assert.match(voiceHook, /export function useChatVoiceInput/, 'useChatVoiceInput hook should be exported');
assert.match(voiceHook, /SpeechRecognition|webkitSpeechRecognition/, 'Voice hook should own browser speech recognition setup');
assert.match(voiceHook, /isLocalSecureContext/, 'Voice hook should keep secure-context gating for microphone access');
assert.match(composer, /data-testid="chat-mention-trigger"/, 'ChatComposer must keep the workspace mention action test id');
assert.match(composer, /placeholder = '有问题，尽管问'/, 'Composer placeholder should stay Chinese');
assert.match(composer, /aria-label="聊天输入框，按 Enter 发送，按 Shift\+Enter 换行"/, 'Composer textarea aria label should be Chinese');
assert.match(composer, /title=\{uploading \? '正在上传文件' : '上传文件'\}/, 'Upload action title should be Chinese');
assert.match(composer, /title="引用工作区数据"/, 'Mention action title should be Chinese');
assert.match(composer, /title="发送消息，按 Shift\+Enter 换行"/, 'Send action title should be Chinese');
assert.match(composer, /className="chat-composer-input-frame"/, 'Composer controls should be wrapped in a stable command-frame');
assert.match(composer, /className="chat-composer-tool-group"/, 'Secondary tools should be grouped for stable spacing');
assert.match(composer, /className="chat-composer-field"/, 'Textarea should sit in a dedicated flexible field');
assert.match(composer, /className="chat-composer-action-cluster"/, 'Primary send and stop actions should have a stable action cluster');
assert.match(composer, /chat-composer-drag-rail/, 'Drag state should have a dedicated visual rail');
assert.match(composer, /data-dragging=\{dragging \? 'true' : 'false'\}/, 'Root should expose drag state without changing behavior');

assert.match(css, /\.chat-composer-input-frame\s*\{[\s\S]*grid-template-columns:\s*auto minmax\(0,\s*1fr\) auto/, 'Composer frame must keep secondary tools, flexible input, and action cluster in stable columns');
assert.match(css, /\.chat-composer-tool-group\s*\{[\s\S]*display:\s*inline-flex/, 'Tool group must use inline-flex for consistent icon spacing');
assert.match(css, /\.chat-composer-tool,\s*\n\.chat-composer-submit\s*\{[\s\S]*height:\s*2\.5rem[\s\S]*width:\s*2\.5rem/, 'Tool buttons and submit should share stable square dimensions');
assert.match(css, /\.chat-composer-field\s*\{[\s\S]*min-width:\s*0[\s\S]*border-radius:/, 'Textarea field must prevent overflow while retaining a visible input surface');
assert.match(css, /\.chat-composer-drag-rail\s*\{[\s\S]*position:\s*absolute/, 'Drag rail must be CSS-only and avoid layout shift');
assert.match(css, /\.chat-mention-menu\s*\{[\s\S]*max-width:\s*calc\(100vw - 1rem\)/, 'Mention menu must be viewport constrained');
assert.match(css, /\.chat-mention-list\s*\{[\s\S]*max-height:\s*min\(18rem,\s*42vh\)/, 'Mention list must be height constrained on small screens');
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.chat-composer-input-frame\s*\{[\s\S]*grid-template-columns:\s*auto minmax\(0,\s*1fr\) auto/, 'Mobile composer must retain upload/mention, input, and send columns');
assert.match(css, /@media \(max-width: 720px\)[\s\S]*\.chat-composer-tool-group\s*\{[\s\S]*\.chat-composer-tool-group \.chat-composer-tool\[data-optional="voice"\]/, 'Mobile layout should hide only the optional voice control');
assert.match(chatPanel, /<ChatComposerFooter/, 'ChatPanel should render the bottom composer through a focused footer component');
assert.doesNotMatch(chatPanel, /chat-quick-prompt/, 'ChatPanel should not own quick-prompt footer markup inline');
assert.match(composerFooter, /export function ChatComposerFooter/, 'ChatComposerFooter should be exported');
assert.match(composerFooter, /data-testid="chat-composer-footer"/, 'Composer footer should expose a stable root test id');
assert.doesNotMatch(composerFooter, /常用指令|chat-quick-prompt-row|quickPrompts\.slice/, 'Composer footer should not render quick prompts in the chat bar');
assert.doesNotMatch(composerFooter, /chat-composer-mode-panel|data-testid="interaction-mode-chat"|data-testid="interaction-mode-tool"/, 'Composer footer should only contain the input capsule after the mode switch moves to the header');
assert.match(conversationHeader, /会话模式/, 'Conversation header should label the mode switch in Chinese');
assert.match(conversationHeader, /data-testid="interaction-mode-chat"/, 'Conversation header must preserve chat mode test id');
assert.match(conversationHeader, /data-testid="interaction-mode-tool"/, 'Conversation header must preserve tool mode test id');
assert.match(conversationHeader, /data-testid="chat-upload-button"[\s\S]*\{modeSwitch\(\)\}/, 'Header mode switch should sit after the upload data action in the page toolbar');
assert.match(css, /\.chat-composer-footer\s*\{[\s\S]*border-top:\s*0/, 'Composer footer should not keep a visible backing plate under the input capsule');
assert.match(css, /\.chat-header-mode-panel\s*\{[\s\S]*display:\s*inline-flex/, 'Header mode switch should have a stable toolbar container');
assert.match(css, /\.chat-interaction-mode-switch\s*\{[\s\S]*display:\s*inline-flex/, 'Mode switch should have a stable segmented-control style');

console.log('chatComposerExperience.test.mjs passed');
